### ISSUE TITLE
Track project health

### ISSUE THREAD

**Issue by crisptrutski** [verma/pani#27]
@verma let's add a test-status badge? You'll need to activate the webhook as admin though.

We'll also need to fix the tests that are timing out (setup valid, public Firebase db)

**Comment by verma** [comment]
Checking public db status

**Comment by verma** [comment]
Seems like there are some problems with the firebase transaction stuff.  When I do a `set!` it seems to emit the correct events but `transaction` just seems to go into a black hole.

Looking into it ...

**Comment by verma** [comment]
Think the the way firebase api behaves may have changed, I just simplified stuff a bit and things seem to be working fine.

**Comment by verma** [comment]
@crisptrutski you mean we should add travis or a similar service right?

**Comment by verma** [comment]
Ok, enabled.

**Comment by crisptrutski** [comment]
:+1: thanks
