### ISSUE TITLE
Clean up API

### ISSUE THREAD

**Issue by crisptrutski** [verma/pani#29]
@verma some ideas about the core namespace to bounce off you:

(excuse the wall of text! just really care about getting this right :thought_balloon: )

1. Most functions on refs are overloaded to take `korks` optionally, but some (eg. `remove`) do not take them and some require them (eg. `bind`). 

  This is confusing and think we should choose one of:

  i. support with-or-without `kork` on all ref functions
  ii. all without, but and we have companion functions which do ((eg `push!` and `push-in!`)
  iii. all without, and leave users to use `walk-root`

2. We have no mechanism to pass a callback to (or receive a channel from) `transact!` or `set!`. Definitely think these are required (eg. "Changes saved" feedback), and possibly other methods too.

3. Some functions are overloaded to take callbacks or return channels, and some only return channels (`listen<`, `value`). While I'm sympathetic to channel-first as idiom, we should be consistent and flexible.

  i. We can't (sanely) use arity-overloading for optional `korks` AND callbacks.
  ii. Dislike return value being based on arity called (like my sugar with less consequences)
  iii. A third case was left out - fire and forget (eg. just want performance or don't care - why make users     pass (and let firebase register) a no-op, or even worse build a channel that immediately goes out of    scope)
  iv. Scenarios where core.async is not suitable (inside core.match ;), or in a project that wants to saves bytes by not including core.async, or wants to use another abstraction like flux actions, generators, bacon.js or node streams).

  This was briefly discussed before at #19 (although around a tangential issue, see 6)

  Proposal:
  i. Have base versions which do not create channels, but take (optional) callbacks.
  ii. Have versions returning new channels, and never taking a callback - in a separate name and/or modified name (eg `base-async`, `base<`,)

4. Representation difference between `listen<` and `bind` (map vs tuple). I prefer tuples (vectors), because that's how clojure represents a map entry (and most convenient for `conj`-ing or destructuring). Bind should maybe even yield `[event-name [key type]]` values? Not sure.

  Other option is to expose a Snapshot prototype over the raw values (lets us expose priority and full path without extending API later). We could also convert to our own record (if JS class is hidden) or even mix solutions - use `specify` to add the prototype to a 2-tuple. (or maybe custom or original type behave like a map entry / 2-tuple? probably just making our lives harder that way around) 

5. Improve function names,

  Certainly a matter of taste, but worth discussing:

  `get-ref` - think we can go with something more primal here, how about `init`?

  `root` (alias) - think we can get rid of this (why alias?). although this is a good point to say: we should choose between `root` and `ref` in our naming - although `ref` is another concept in clojure (but not clojurescript), I think it's the better choice (makes it clear "everything is relative" and matches javascript docs)

  `walk-root` - maybe meant to be internal, but I like to use it in my programs. think this should wrest the `get-in` name from its sibling

  `name` - this should become `key`, saves a `clojure.core` clash and follows js library

  `parent` - (no complaints)

  `value` - it's a lot like `deref` (except that makes it sound synchronous),  maybe `take!` (but confusing when taking callback). there's also `listen-once` I guess.

  `get-in` - see (1), should either be overloaded or following naming pattern from whatever `value` gets called.

  `set!` - (no complaints).. except issue that it can't be called without namespacing, gets mistaken for interop. another option is `reset!`, to match atom.

  `push!` - (no complaints).. but `conj` could also work. (also maybe we want something like `into` for appending seqs?)

  `remove!` - (no complaints) matches underlying lib and `goog.object.remove` for interop on #js `delete`.

  `bind`  - too overloaded (`function.bind(this, ...)` in js, dynamic scopes in clojure, key-bindings in client-side apps, etc). `on` is pretty standard (jQuery gorilla) but sounds strange for creating a channel. I think this is more deserving of `listen` than it's peer. Could also appeal to datomic/om - `tx-listen`

  `transact!` - (no complaints).. but another option is `swap!`  to reference atoms/transients.

  `listen<` - see `bind`, how about `listen-to` or similar prefix to denote the scoping (and removing of event-name label from values).
  
6. Slightly tangential - queries. Only affects us here if we decide existing methods could benefit from overloading to utilise this feature (I'm thinking `listen` and `value`).

Appreciate that a lot of the naming I'm attacking comes from allusion to Om - that's actually what made the library striking to me and piqued my interest (had not used Firebase), but feel there's an even more elegant API trying to get out :)

Hopefully this mind dump isn't too typo riddled and makes some sense!

**Comment by crisptrutski** [comment]
@verma ping (impatient to cut a release :smiley_cat:)

**Comment by verma** [comment]
@crisptrutski sorry, in a code sprint this week, so totally non-responsive :(.

Thanks for taking the time to write all that up!  I do feel that the current API has been a culmination of trial and error and me learning (and you helping!) Clojure in the process.  I agree with the sentiment that its time to make this elegant and get rid of (and avoid) inconsistencies. 

1.  I agree, I'd personally be most comfortable with ii, modeling after get/get-in from core.  But I am not really biased. iii. is least attractive to me for some reason.
 
2/3.  I agree, following up on the stuff you discuss in point 3, I feel being explicit about what a particular variation of a function does is a good way imho.  `transact!` and `set!` can model after it as well.  I agree with your proposal for 3, just not sure `base-async` or `base<`, following up on whatever convention for naming functions that return channels, I would be inclined towards `base<`.

4.  Yes, consistency is definitely desirable here, have come across it myself several times :)  I know a result ref we get from firebase has much more information than we expose right now and may be having it wrapped around with our own protocol/defrecord stuff would be nice!  But I would then probably want these refs being used everywhere (e.g. `set!`, `transact!` etc.).  It is definitely more powerful and I feel kind of uncomfortable jumping the gun on it, may be settle for consistent primitive type for now, and brood over it a little bit, and may be try to get it figured before we get to 1.x releases :)

5.  I generally agree with all naming updates, I particularly like the `conj` idea :) .. my goal initially with pani had never been to expose firebase API .. so I am always more inclined towards making it more clojurey and I think this is a nice example of that! :) (also why I called things `root` and `walk-root`).  I guess it made more sense to me when I first decided to name things, but I can understand that it could get confusing for people who basically want to use firebase more conveniently from clojure(script) and don't want or care about my half-baked abstractions over it :)  I would say feel free to change names as you find them appropriate, my general guideline has been to make it more clojuery and not fall prey to how the firebase API is naming things, sometimes it makes sense and sometimes it doesn't, which always sucks :(

6.  Ooooh, I never knew they existed, are you referring to this: https://www.firebase.com/blog/2013-10-01-queries-part-one.html ?  I see much fun adventures into composition with this, but I know almost nothing about it so have no opinions at this time, sorry :(

Again, thanks so much for taking the time and investing your efforts into this!  I appreciate it and I am sure with your insights and work into this, future users of this library will do so too :)

**Comment by crisptrutski** [comment]
Great! Didn't expect us to agree on so much :) Will plough the the lowest hanging of the fruit and prepare 0.0.4 tonight

**Comment by martinklepsch** [comment]
Didn't read everthing but I welcome some spring cleaning :dolphin: :+1:

**Comment by crisptrutski** [comment]
@martinklepsch mind skimming the linked PR? Would really value your fresh and lofty insights :statue_of_liberty: 

How's your Firebase feeler project going? Any pain points you'd want a library to veneer?
