### ISSUE TITLE
Clojure API to catch up with ClojureScript

### ISSUE THREAD

**Issue by verma** [verma/pani#3]
More child event listeners are needed for Clojure.

**Comment by crisptrutski** [comment]
@verma what do you think of introducing CLJX to ease keeping the two runtimes in sync (and perhaps even sharing a public-api namespace)?

**Comment by verma** [comment]
@crisptrutski I have tried it in the past and failed at it :( .. The Firebase API for Java and JS were significantly different because of which I (eventually) didn't see any value in using it.  Being able to share a namespace would be nice :).

I have no problems with it otherwise.

**Comment by crisptrutski** [comment]
Moved here: https://github.com/crisptrutski/sunog/issues/3
