### ISSUE TITLE
bind only returning .val not .name

### ISSUE THREAD

**Issue by Cottin** [verma/pani#9]
BTW, great project! Makes Firebase development fun in clojure!

When binding to e.g. `:child-added` like so:

```
(pani/bind r :child_added :ideas #(log "child-added:" %0 %1 %2 %3)))
```

Only the value of the child is returned, the name (id) of the firebase child is not there.

Example console output:

```
child-added:{:title "Ide nr 2"}
child-added:{:title "Ide nr 1"} 
```

My guess is that the `bind` can't only do a `clj-val` it needs to do a `clj-name` also ?

```
(defn bind
  "Bind to a certain property under the given root"
  ([root type korks]
   (let [bind-chan (chan)]
     (bind root type korks #(go (>! bind-chan %)))
     bind-chan))

  ([root type korks cb]
   (let [c (walk-root root korks)]
     (.on c (clojure.core/name type) 
          #(when-let [v (clj-val %1)]
             (cb v))))))
```

Reference: https://www.firebase.com/docs/web/guide/retrieving-data.html#section-event-types

Also, the project does not `cljsbuild`:

```
git clone https://github.com/verma/pani.git
cd pani
lein cljsbuild once
```

results in:

```
Compiling "examples/cljs/om-value-changes/main.js" failed.
clojure.lang.ExceptionInfo:  {:tag :cljs/analysis-error}
    at clojure.core$ex_info.invoke(core.clj:4327)
    ...
Caused by: java.lang.NullPointerException
```

Do I need to do a special kind of build?

**Comment by tgatga007-ui** [comment]
> BTW, great project! Makes Firebase development fun in clojure!
> 
> When binding to e.g. `:child-added` like so:
> 
> ```
> (pani/bind r :child_added :ideas #(log "child-added:" %0 %1 %2 %3)))
> ```
> 
> Only the value of the child is returned, the name (id) of the firebase child is not there.
> 
> Example console output:
> 
> ```
> child-added:{:title "Ide nr 2"}
> child-added:{:title "Ide nr 1"} 
> ```
> 
> My guess is that the `bind` can't only do a `clj-val` it needs to do a `clj-name` also ?
> 
> ```
> (defn bind
>   "Bind to a certain property under the given root"
>   ([root type korks]
>    (let [bind-chan (chan)]
>      (bind root type korks #(go (>! bind-chan %)))
>      bind-chan))
> 
>   ([root type korks cb]
>    (let [c (walk-root root korks)]
>      (.on c (clojure.core/name type) 
>           #(when-let [v (clj-val %1)]
>              (cb v))))))
> ```
> 
> Reference: https://www.firebase.com/docs/web/guide/retrieving-data.html#section-event-types
> 
> Also, the project does not `cljsbuild`:
> 
> ```
> git clone https://github.com/verma/pani.git
> cd pani
> lein cljsbuild once
> ```
> 
> results in:
> 
> ```
> Compiling "examples/cljs/om-value-changes/main.js" failed.
> clojure.lang.ExceptionInfo:  {:tag :cljs/analysis-error}
>     at clojure.core$ex_info.invoke(core.clj:4327)
>     ...
> Caused by: java.lang.NullPointerException
> ```
> 
> Do I need to do a special kind of build?
